// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://negmvyuowzqobzpidpbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lZ212eXVvd3pxb2J6cGlkcGJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjQ5OTEsImV4cCI6MjA3Mjc0MDk5MX0.SCxXxVvm5NgNQs96jJfYVlxGbern43cG93bQsCbfpow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});